Rails.application.config.spotlight = OpenStruct.new
Rails.application.config.spotlight.activities = [
  "sing",
  "learn to play a musical instrument",
  "organise a sing-a-long movie night",
  "start a band",
  "start an a capella group",
  "go to a concert",
  "go to an open mic night",
  "organise a battle of the bands",
  "write songs",
  "host a rap battle",
  "learn to dj",
  "grow a garden",
  "plant some trees",
  "make a community compost",
  "grow fruit and veg",
  "look after local bees",
  "plant a communal herb garden",
  "share a chicken",
  "bulk buy food",
  "weed a community garden",
  "repair footpaths",
  "start a seed library",
  "share bee friendly plant cuttings",
  "share my tools",
  "borrow some tools",
  "make handmade gifts",
  "repair my clothes",
  "fix some electronics",
  "upcycle some old furniture",
  "put up a wind turbine",
  "organise a street party",
  "go to an exercise class",
  "go walking",
  "go cycling",
  "organise a football competition",
  "stay healthy",
  "learn how to repair my bike",
  "go hiking",
  "go for a run",
  "walk a neighbour's dog",
  "learn to fix my broken phone",
  "learn how to print my own cards",
  "learn how to cook",
  "learn another language",
  "learn how to use social media",
  "learn about crypto currencies",
  "learn creative writing skills",
  "teach people a new skill",
  "learn to cook new things",
  "meet new people and enjoy food together",
  "experience food from around the world",
  "develop healthy eating habits",
  "teach a recipe",
  "batch cook some food",
  "batch cook baby food",
  "participate in supper clubs",
  "discuss veganism",
  "make cider",
  "host a potluck dinner",
  "organise a nearly new toy swap",
  "start a babysitting club",
  "start a toy exchange",
  "share baby tips",
  "swap baby clothes",
  "host a birthday party",
  "go to a show",
  "organise to closed the street for playing",
  "put on an outdoor cinema night"
]
